platform :ios, '10.0'

project 'BasicPlayerSample.xcodeproj'

use_frameworks!

target 'BasicPlayerSample' do
  pod 'AEPCore', :git => 'https://github.com/adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPServices', :git => 'https://github.com/adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPRulesEngine', :git => 'https://github.com/adobe/aepsdk-rulesengine-ios.git', :branch => 'main'
  pod 'AEPIdentity', :git => 'https://github.com/adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPLifecycle', :git => 'https://github.com/adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'ACPCore', :git => 'https://github.com/adobe/aepsdk-compatibility-ios.git', :branch => 'main'
  pod 'AEPMedia', :git => 'https://github.com/adobe/aepsdk-media-ios.git', :branch => 'dev'
  pod 'AEPAssurance'
  pod 'AEPAnalytics'
end
